name: Validate Pull Request
on: 
  pull_request:
jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - uses: ricardo100671/_salesforce_cicd/validate.yml@main
        with:
          sfUser: 
          sfConsumerKey: 
          path: force-app/**